### ISSUE TITLE
New Version finds Mesa instead of Desert. And where's the compass?

### ISSUE THREAD

**Issue by Knito58** [MattCzyr/NaturesCompass#3] opened 2017-07-08 14:12 UTC
MC 1.12
Forge 14.21.1.2402
NC 1.12-1.4.0

Yay it finally is on 1.12! Needed sand and wanted a desert biome. Where is the compass gone? It is just a rod now. Clicking "info" tells me nothing about that rod. Tried to guess what the right direction could be when it changed from light to dark. But as it turned out, the coloring is rather done randomly. After going into the wrong direction I concentrated on the position said by Nature's Rod and Journey Map's position indicator. I found it finally. I mean, I found the position where Nature's Rod told "distance: zero". It was a Mesa.
There was also some red sand so I'm happy now.

**Comment by MattCzyr** [comment] 2017-07-08 15:27
Can you post some screenshots of the compass texture issue? I have not been able to reproduce it. Also, can you press F3 at the location the compass takes you to (when it says zero on the HUD) and see if the biome there is indeed categorized as a desert? It's possible that a few blocks of the mesa are actually labelled as a desert biome, despite not showing characteristics of a desert.

**Comment by Knito58** [comment] 2017-07-09 05:44
Here's the texture: https://www.dropbox.com/s/pnpoxg7akjsfdax/naturesrod.jpg?dl=1

Desert-Fault: OK I was hypersensitive and did over-react a little bit. It is a very small desert whith mesa blocks beside. Didn't recognize  it as such. My fault.

https://www.dropbox.com/s/fivruybik3edunc/ncdesert1.jpg?dl=1
https://www.dropbox.com/s/3uf0v8l55i4k3xe/ncdesert2.jpg?dl=1

**Comment by MattCzyr** [comment] 2017-07-09 06:18
What texture pack are you using? It seems to me that the texture pack must be changing the compass texture. Can you try disabling your texture pack and see if the compass texture returns to normal?

**Comment by billybricker** [comment] 2017-07-09 12:35
I'm having issues with the texture in 1.12 as well. It's just a broken texture for me, standard purple and black.


![2017-07-08_23 00 22](https://user-images.githubusercontent.com/26291936/27993970-bce8034e-6470-11e7-9093-3f708189f5c7.png)
![2017-07-08_23 00 31](https://user-images.githubusercontent.com/26291936/27993971-bce8b0fa-6470-11e7-8328-224fb465896c.png)

**Comment by MattCzyr** [comment] 2017-07-09 15:41
Could you both try running the game with just Nature's Compass installed? I.E. make a new instance and run the game with just the one mod installed, then make a new world and test the texture there. I'm still unable to recreate this issue myself, which makes it very difficult to get to the bottom of it.

When I run the game with the same Forge version as the issue was created with, the texture is just fine. The only thing different about our environments should be the other mods we have installed (I have none).

![2017-07-09_11 30 52](https://user-images.githubusercontent.com/14143296/27995343-a7f19282-649a-11e7-8559-7badf6eca261.png)

**Comment by Knito58** [comment] 2017-07-09 19:44
I renamed my mods folder and restarted Minecraft. In the freshly generated, empty mod folder I put the NC 1.4.0 mod. In a new creative world now the compass is back!
![Its again a compass](https://www.dropbox.com/s/ac8904d7c6yqyc0/oldcompass.jpg?dl=1)
Ooaaah... Never had a frozen river biome like that! And that is non-modded vanilla!

**Comment by Knito58** [comment] 2017-07-09 19:46
Now don't even think about asking me to drop my 100 mods one by one in until the texture is gone!
No!
:) :P

**Comment by Knito58** [comment] 2017-07-09 19:51
I do not mod anymore since years. Maybe this is an ID-conflict? Possibly a registering problem which allows Forge to swap the resource with anything randomly found? Just guessing....

**Comment by billybricker** [comment] 2017-07-10 15:20
@MattCzyr The texture seems fine without any other mods installed. Not sure which mod could be causing it to break, or how, but I don't really feel like debugging that right now as I've got like 100 mods installed. If I happen to figure out which mod is causing it I'll be sure to let you/them know.

**Comment by Knito58** [comment] 2017-07-11 21:07
I finally found the mod which replaces the texture in my case. It is "Omega Craft".
![Found it](https://www.dropbox.com/s/r96seup9eerfr2e/nc_rod_found.jpg?dl=1)

**Comment by MattCzyr** [comment] 2017-07-12 04:11
Can you confirm that the texture works as intended with all your other mods installed except Omega Craft? That mod is definitely adding the texture that Nature's Compass is somehow using, but please make sure that mod is actually causing the issue itself.

**Comment by Knito58** [comment] 2017-07-12 17:00
Yes, it looks as if for my case it would be Omega Craft to blame. As there are multiple Omega-Named-Mods out, I put the linke here: https://minecraft.curseforge.com/projects/omega-craft-mod?gameCategorySlug=mc-mods&projectID=261442

![100 mods but no Omega Craft](https://www.dropbox.com/s/zkd63wi72md7d88/nc_without_omega.jpg?dl=1) 

@billybricker: You have OmegaCraft and would uninstall it for testing?

**Comment by billybricker** [comment] 2017-07-12 17:03
I do not have OmegaCraft so that's not what's causing the broken texture on my end.

**Comment by Knito58** [comment] 2017-07-12 17:09
Bof. :P

**Comment by billybricker** [comment] 2017-07-12 17:19
Since the texture appears to be fixed for you can I get your mod list? I'm probably going to look into this a bit tonight and having your mod list would probably make my job easier by ruling out anything we have in common.

**Comment by Knito58** [comment] 2017-07-12 17:56
My modlist:

[1.12]UncraftingTable-1.8-beta3.jar
ActuallyAdditions-1.12-r114.jar
Aroma1997Core-1.12-1.3.0.0.b94.jar
Aroma1997s-Dimensional-World-1.12-1.3.0.0.b37.jar
AromaBackup-1.12-2.1.0.0.b71.jar
astralsorcery-1.5.8.jar
atmlib-1.2.0.jar
AutoRegLib-1.3-13.jar
BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar
BiblioCraft[v2.4.2][MC1.12.0].jar
Bookshelf-1.12-2.0.0.412.jar
Calculations-1.12-1.1.0.jar
Chameleon-1.12-4.1.1.jar
ChestTransporter-1.12-2.8.3.jar
CodeChickenLib-1.12-3.1.0.278-universal.jar
CoFHCore-1.12-4.3.2.7-universal.jar
CoFHWorld-1.12-1.0.0.5-universal.jar
cxlibrary-1.12-1.5.1.jar
CyclopsCore-1.12-0.10.7.jar
DarkUtils-1.12-1.6.158.jar
dooglamoocitiesmod-1.12-1.6.2.jar
DungeonDQ_Ver9.40_[MC1.12](forge-1.12-14.21.1.2387).jar
DynamicSurroundings-1.12-3.4.5.7.jar
EverlastingAbilities-1.12-1.3.1.jar
forestry_1.12-5.4.3.129.jar
Forgelin-1.5.0.jar
GravelMiner_1.12-6.1.1.jar
gravestone-1.8.4.jar
Growable Cells-1.12-2.3.1.jar
ImprovedBackpacks-1.12-1.1.2.0.jar
intwheel-1.12-1.2.7.jar
InventoryTweaks-1.63+dev.105.jar
ironchest-1.12-7.0.31.818.jar
jei_1.12-4.7.1.75.jar
journeymap-1.12-5.4.9.jar
LLOverlayReloaded-1.1.4-mc1.12.jar
lostcities-1.12-0.0.17beta.jar
mbm-Master_Builders_Mod_v.1.9.0.1A-01_1.12.jar
mcjtylib-1.12-2.4.3.jar
MoreFurnaces-1.12-1.10.1.jar
multistorage-1.12.0-1.4.0.1.jar
mysticalagriculture[1.12]-1.6.1a.jar
NaturesCompass-1.12-1.4.0.jar
Neat 1.4-15.jar
NetherEx-1.12-2.1.4.5.jar
notenoughwands-1.12-1.5.9.jar
Notes-1.12-1.1.1.jar
Omega Craft 2.2.1 - 1.12.jar
OverpoweredInventory-1.12-2.3.1.jar
packetfilter-1.6.3.jar
PetBat-1.12.jar
platforms-1.12.0-1.4.0.1.jar
QuantumStorage-1.12-4.3.4.jar
Quark-r1.2-100.jar
RandomThings-MC1.12-4.0.2.jar
RebornCore-1.12-3.2.4.86-universal.jar
RedstoneFlux-1.12-2.0.0.1-universal.jar
RefinedRelocation_1.12-4.1.4.jar
refinedstorage-1.5.8.jar
ReinforcedTools-2.1.0.jar
rftools-1.12-6.10beta4.jar
roots-2-0.025.jar
RottenFleshToLeather [0.0.4].jar
Scannable-MC1.12-1.4.0.5.jar
shetiphiancore-1.12.0-3.5.0.1.jar
Simple Item Collector Chest-0.2.1.jar
SimpleGrinder-4.050.R112.jar
SimpleStorageNetwork-1.12-1.0.10.jar
simpleteleporters-1.12-2.1.5.jar
Simple-Void-World-1.12-1.2.0.1-universal.jar
StevesCarts-1.12-2.4.4.25.jar
StorageDrawers-1.12-5.2.7.jar
SuperMiner-2.5.33.325.jar
TamModized-1.12-0.13.7.jar
theoneprobe-1.12-1.4.12.jar
ThermalDynamics-1.12-2.3.2.9-universal.jar
ThermalExpansion-1.12-5.3.2.10-universal.jar
ThermalFoundation-1.12-2.3.2.8-universal.jar
ViesCraft-1.12.0-5.0.0.jar
VoidCraft-1.12-0.23.2.jar
VTweaks-1.12-1.4.11.3.jar
WaterPower-1.12-0.5.4.jar
Wither Skeleton Tweaks-1.12-2.2.2.jar
WTS-1.1.0.jar
xnet-1.12-1.3.5.jar
YukariLib-1.12-1.3.0.jar

**Comment by billybricker** [comment] 2017-07-12 18:02
Perfect, thanks! I'll do some testing when I get home from work.

**Comment by Knito58** [comment] 2017-07-12 19:51
You're welcome :)

**Comment by Knito58** [comment] 2017-07-12 22:24
The texture is not fixed for me as I do not doom Omega Craft yet. I set a waypoint into the journeymap when a biome is found. Maybe that would be a suggestion? NC puts waypoint into JM when configured so?
Waypoint seems to be json files in .minecraft/journeymap/data/sp/<worldname>/waypoints/<waypointname>_<x>,<y>,<z>.json

You could make the NC waypoints colour configurable. And then fill in the data found by the NC when a new search is done with checked checkbox "set JM waypoint".  Dunno if its enough to create such a waypoint file or if something else like "now, dear JM, read all the waypoints again" is needed.

**Comment by billybricker** [comment] 2017-07-12 22:36
@MattCzyr After some testing it looks like Flat Colored Blocks is breaking the texture somehow. Removing the mod from my pack fixed it.

**Comment by MattCzyr** [comment] 2017-07-12 23:20
Thanks for narrowing it down to those specific mods, and thanks for the suggestion @Knito58. I'll look into this issue and see if there's anything I can do. It does seem to be specific to 1.12, despite (seemingly) nothing in the texture system changing in the update (at least on my end).

**Comment by Knito58** [comment] 2017-07-13 15:09
OmegaCraft doomed. I found I never got into it and never did anything with it. Trying to keep my mod count under 100. Thanks for investigating the waypoint suggestion.
Thanks MattCzyr, thanks billybricker!

**Comment by Greytusks** [comment] 2017-07-17 14:32
Additional info if it helps. This issue also occurs when using this pack : FTB Unstable 1.12 version 1.0.2

**Comment by MattCzyr** [comment] 2017-07-24 04:03
I think I've finally gotten to the bottom of this mismatched texture issue. Look for a new release in the next couple days.

**Comment by Knito58** [comment] 2017-07-24 15:20
Great!

**Comment by MattCzyr** [comment] 2017-07-24 23:57
Should be fixed in version 1.5.0. Let me know if it persists with any configuration of mods.

**Closed** 2017-08-09 23:40 UTC
