### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by slard3** [MattCzyr/NaturesCompass#56] opened 2020-02-15 15:13 UTC
Full report: https://hastebin.com/ucelozeqoz.pl

Minecraft Version: 1.15.2
Forge: 31.1.0
NaturesCompass-1.15.1-1.8.3.jar

I simply crafted it, right-click'd it, searched for mushroom fields, chose that option and it crashed. Maybe it's a mod compat issue (but I've been using most of these mods together over a week now, and the compass didn't cause any problems before) so it isn't even worth checking it, but here it is anyways

**Comment by MattCzyr** [comment] 2020-03-02 03:15
I've been unable to replicate this issue myself but I think I've gotten to the bottom of it. Please replace your Nature's Compass jar file with this one and let me know if the issue is fixed or if it persists:

https://www.dropbox.com/s/2lz3pxta1gtdua9/NaturesCompass-1.15.2-1.8.5-beta.jar?dl=0

**Comment by MattCzyr** [comment] 2020-03-03 00:16
Fixed in version 1.8.5

**Closed by MattCzyr** 2020-03-03 00:16 UTC
Labels: bug
