### ISSUE TITLE
1.12.2 Server crash

### ISSUE THREAD

**Issue by EnterFor** [MattCzyr/NaturesCompass#55] opened 2020-02-07 13:45 UTC
https://paste.ubuntu.com/p/x9Wdqc28MX/

Mod Version：NaturesCompass-1.12.2-1.8.3.jar
Forge Version：2847

**Comment by sicariusdracus** [comment] 2020-02-28 19:19
https://paste.dimdev.org/aqutakuyay.mccrash

Running MC.Eternal 
Forge Version 2847

I had just used the compass to locate a biome, found nothing and then interacted with a small crate. World doesn't appear to be reloadable. (Thank you server backups)

**Comment by MattCzyr** [comment] 2020-03-02 03:14
I've been unable to replicate this issue myself but I think I've gotten to the bottom of it. Please replace your Nature's Compass jar file with this one and let me know if the issue is fixed or if it persists:

https://www.dropbox.com/s/afiq0b6cr503etg/NaturesCompass-1.12.2-1.8.5-beta.jar?dl=0

**Comment by sicariusdracus** [comment] 2020-03-02 04:42
Yes that enabled the world to load.

**Comment by MattCzyr** [comment] 2020-03-03 00:15
Fixed in version 1.8.5

**Closed by MattCzyr** 2020-03-03 00:15 UTC
Labels: bug
