### ISSUE TITLE
Crash when using Nature's Compass

### ISSUE THREAD

**Issue by SlashClaw14** [MattCzyr/NaturesCompass#58] opened 2020-02-27 02:02 UTC
Crash report: https://pastebin.com/qcDX1WWD

Minecraft 1.12.2
NaturesCompass-1.12.2-1.8.3
Forge 14.23.4.2847

Not sure if it's because of an incompatibility or not, but it's happened twice now. I was searching for a jungle and then put the item in my offhand. I moved a little bit and the compass needle moved too, but then the game froze and crashed. When I reloaded the game after the first time, the item disappeared from my inventory. The second time it was still in my offhand, however.
EDIT: It also crashes when it's in my hotbar, so it's not an issue exclusive to the offhand.

**Comment by MattCzyr** [comment] 2020-03-02 03:16
I've been unable to replicate this issue myself but I think I've gotten to the bottom of it. Please replace your Nature's Compass jar file with this one and let me know if the issue is fixed or if it persists:

https://www.dropbox.com/s/afiq0b6cr503etg/NaturesCompass-1.12.2-1.8.5-beta.jar?dl=0

**Comment by MattCzyr** [comment] 2020-03-03 00:16
Fixed in version 1.8.5

**Closed by MattCzyr** 2020-03-03 00:16 UTC
Labels: bug
