### ISSUE TITLE
Server crash, not sure what caused it

### ISSUE THREAD

**Issue by katubug** [MattCzyr/NaturesCompass#26] opened 2019-04-17 04:42 UTC
A player and I were both looking at the Nature's Compass, trying to get the search function to work, when the server encountered this crash:

[crash-2019-04-16_23.37.29-server.txt](https://github.com/MattCzyr/NaturesCompass/files/3087946/crash-2019-04-16_23.37.29-server.txt)

Please let me know if I can provide any more info.

**Comment by katubug** [comment] 2019-04-17 04:44
Wait, I think I figured it out. I must have clicked on the top biome in the screenshot.

![2019-04-16_23 43 42](https://user-images.githubusercontent.com/20935286/56261655-7e829900-60a1-11e9-801a-d1cd6dfedcaf.png)

**Comment by MattCzyr** [comment] 2019-05-09 04:55
Looks like a duplicate of #22 and #20. If you're still experiencing this issue can you try using this beta version instead, replicate the issue under the same conditions, and let me know what happens?

https://www.dropbox.com/s/m0pqzaoi0oze88d/NaturesCompass-1.12.2-1.5.2-beta.jar?dl=0

**Comment by katubug** [comment] 2019-06-08 01:25
I somehow missed this response, my sincere apologies! I saw in the other issue that the person reported the crash was fixed with the beta file. Would you still like me to test it out and get back to you?

**Closed** 2019-12-03 01:42 UTC
