### ISSUE TITLE
Server crash when searching for a biome

### ISSUE THREAD

**Issue by Wohlf-craft** [MattCzyr/NaturesCompass#48] opened 2019-12-17 00:33 UTC
I think I just saw another issue related to this. I might have not looked hard enough but I didn't see the same cause. Anyways this happens after I have searched for a biome.
https://gist.github.com/Wohlf-craft/3db2111db80092fb1e91c57f7811a0c2

Edit: I forget to mention but I am using a standard forge server. Latest forge and version of the mod. I don't know if it works with other mods or not.

**Comment by MattCzyr** [comment] 2019-12-17 01:30
Just to confirm, you are using version 1.6.2? Thought this issue was fixed in that version.

Would you mind posting the crash report `crash-2019-12-16_17.52.53-server.txt`?

**Comment by Wohlf-craft** [comment] 2019-12-17 17:35
No I have the version on 1.6.0

**Comment by MattCzyr** [comment] 2019-12-17 21:43
Please update to 1.6.0 and let me know if the problem is resolved.

**Comment by Skwuruhl** [comment] 2020-01-13 08:28
I was running a modpack with 1.6.0 and manually updated it to the newest version and that fixed it.

**Comment by MattCzyr** [comment] 2020-01-13 19:43
Marking this as resolved, in that case

**Closed by MattCzyr** 2020-01-13 19:43 UTC
Labels: bug, info needed
