### ISSUE TITLE
Crash when using compass

### ISSUE THREAD

**Issue by Ravalli03** [MattCzyr/NaturesCompass#33] opened 2019-10-08 00:00 UTC
I get this crash when trying to search a biome

https://pastebin.com/juEhJ1Hf

MC- 1.12.2
Nature's Compass- 1.5.1
forge-14.23.5.2838

**Comment by MattCzyr** [comment] 2019-10-09 22:32
Duplicate of #20, #22, and #26, will be fixed in version 1.5.2.

**Closed** 2019-10-09 22:32 UTC
Labels: duplicate
